name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect Changes in Services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect Changed Services
        id: detect
        run: |
          # Detect changed directories under 'services'
          services=$(git diff --name-only HEAD^ HEAD | grep '^services/' || true cut -d'/' -f2 | sort | uniq)
          if [ -z "$services" ]; then
            echo "[]" > services.json
          else
            echo "[\"$(echo $services | tr ' ' '\",\"')\"]" > services.json
          fi
          echo "Services detected:"
          cat services.json
        shell: bash
      
      - name: Set Output for Services
        id: set-output
        run: echo "services=$(cat services.json)" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and push Docker images
    needs: detect-changes
    runs-on: 
      - ubuntu-latest
    #if: ${{ fromJson(needs.detect-changes.outputs.services) != '[]' }}
    
    # strategy:
     # matrix:
     #   service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    #continue-on-error: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: test fromJson
        run: |
          echo '${{ fromJson(needs.detect-changes.outputs.services) }}'

      - name: Log in to Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: services/message-uploader # services/${{ matrix.service }}
        run: |
          docker build -t yuvalrabo/message-uploader:${{ github.sha }} .
          docker tag yuvalrabo/message-uploader:${{ github.sha }} yuvalrabo/message-uploader:latest
          docker push yuvalrabo/message-uploader:${{ github.sha }}
          docker push yuvalrabo/message-uploader:latest    