name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "building a docker image"

    runs-on: 
      - ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker Image
        run: |
          docker build -t request-validator:${{ github.sha }} .
          docker tag request-validator:${{ github.sha }} yuvalrabo/request-validator:latest

      - name: Push Docker Image to DockerHub
        run: |
          docker push yuvalrabo/request-validator:${{ github.sha }}
          docker push yuvalrabo/request-validator:latest
