name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect Changes in Services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Changed Services
        id: detect
        run: |
          # Detect changed directories under 'services'
          services=$(git diff --name-only HEAD^ HEAD | grep '^services/' | cut -d'/' -f2 | sort | uniq)
          echo "services=$services"
          echo "::set-output name=services::$services"

  build-and-push:
    name: Build and push Docker images
    needs: detect-changes
    runs-on: 
      - ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    continue-on-error: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: services/${{ matrix.service }}
        run: |
          docker build -t yuvalrabo/${{ matrix.service }}:${{ github.sha }} .
          docker tag yuvalrabo/${{ matrix.service }}:${{ github.sha }} yuvalrabo/${{ matrix.service }}:latest
          docker push yuvalrabo/${{ matrix.service }}:${{ github.sha }}
          docker push yuvalrabo/${{ matrix.service }}:latest    